name: Playwright CI

on:
  push:
    branches: [main]

jobs:
  Run_Script:
    runs-on: [self-hosted, macOS, uat, playwright]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npx playwright install

      - run: npx playwright test

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/


  Report:
    name: Report
    needs: Run_Script
    runs-on: ubuntu-latest

    steps:
      - name: Download report
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Generate Report Summary
        run: |

          REPORT=playwright-report/results.json
          PASSED=$(jq '.stats.expected' $REPORT)
          FAILED=$(jq '.stats.unexpected' $REPORT)
          SKIPPED=$(jq '.stats.skipped' $REPORT)
          TOTAL=$((PASSED + FAILED + SKIPPED))

          echo "## ðŸ§ª Test Report Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Status | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| âœ… Passed | $PASSED |" >> $GITHUB_STEP_SUMMARY
          echo "| âŒ Failed | $FAILED |" >> $GITHUB_STEP_SUMMARY
          echo "| â­ Skipped | $SKIPPED |" >> $GITHUB_STEP_SUMMARY
          echo "| ðŸ“Š Total | $TOTAL |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "â± **Duration:** 3.2s" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY


  Send_Mail:
    name: Send_Mail
    needs: Report
    runs-on: ubuntu-latest

    steps:
      - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true

          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}

          subject: "Playwright Test Result - ${{ needs.Run_Script.result }}"

          to: bigkk2008@hotmail.com
          from: Playwright CI <${{ secrets.MAIL_USERNAME }}>

          body: |
            Playwright CI Finished ðŸš€

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Status: ${{ job.status }}


            View report:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
